x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: ${LOGGING_MAX_SIZE:-5M}
      max-file: ${LOGGING_COUNT_FILES:-10}

x-network: &network
  networks:
    - all-net

services:
  certbot:
    <<: [*logging, *network]
    image: ghcr.io/adam-sizzler/certbot:${CERTBOT_VERSION:-latest}
    container_name: certbot
    volumes:
      - haproxy-socket:/var/run/haproxy
      - certificate:/etc/letsencrypt
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -n \"$$DOMAIN_NAME\" ] && [ -s /etc/letsencrypt/live/$$DOMAIN_NAME/haproxy.pem ]"]
      interval: 20s
      timeout: 5s
      retries: 3
    profiles: [full, certbot]

volumes:
  haproxy-socket:
    name: haproxy-socket
    driver: local
  certificate:
    name: certificate
    driver: local

networks:
  all-net:
    driver: bridge
